### ISSUE TITLE
Multiple dependent menus causes multiple AJAX calls

### ISSUE THREAD

**Issue by phptek** [sheadawson/silverstripe-dependentdropdownfield#12]
Firefox 42 / Ubuntu 14.12

Using x2 sets of `DependentDropdownFields` in the frontend causes x2 AJAX requests to be sent each time an `onchange` event is fired. This seems to be a problem with `entwine` and not the module's custom JS logic per se - as I can chuck a `console.log('#TEST')` right after `onadd` and that will output "#TEST" _4_ times (But cannot figure out why in the few minutes of debugging I've had time to do)

**Comment by IrinaStr** [comment]
Hi, I have the same problem.. did you figured it out? Would be great if you could share your solution! :)

**Comment by nyeholt** [comment]
I've actually got a locally patched version of the module that uses onmatch instead of onadd and it works fine; I'm not sure of the difference in how entwine handles those two events though?

**Comment by bimah** [comment]
That's not to do with entwine but the way the js is constructed...

The class `.dependent-dropdown` get added to the external container and to the dropdown so when you call  `$(".dependent-dropdown").entwine({});` it get call twice.

I solved it by checking if the element has `data-depends` attribute by wrapping the function in
`if(drop.data('depends')){}`

I hope this help

**Comment by sheadawson** [comment]
Fixed in #24
