### ISSUE TITLE
Keeps loading

### ISSUE THREAD

**Issue by hesteric** [sheadawson/silverstripe-dependentdropdownfield#5]
Hi, this is the module I need :)

But when I select something in the first dropdown, the depended dropdown shows Loading and futher nothing. This is my code:

        public function getFields() {

        $datesSource = function($val){
            if($val == 1){
                array(
                    'NZ' => 'New Zealand',
                    'US' => 'United States',
                    'GEM'=> 'Germany'
                );
            }
            if($val == 2){
                array(
                    'NZ' => 'New Zealand',
                    'US' => 'United States',
                    'GEM'=> 'Germany'
                );
            }
        };

        $TypeOfProductField = DropdownField::create('TypeOfProduct', 'Type of product', ProductCategory::get()->map('ID', 'Name'))
            ->setEmptyString('(Select one)');

        $ProductSpecificationField = DependentDropdownField::create('ProductSpecification', 'Product specification', $datesSource)
            ->setDepends($TypeOfProductField);

        return new FieldList(
            $TypeOfProductField,
            $ProductSpecificationField
        );

    }

See a screenshot in the attachment as well.
![screenshot](https://cloud.githubusercontent.com/assets/6453793/5942541/8902a0f6-a718-11e4-9370-0dfbdcb902ca.jpg)

**Comment by sheadawson** [comment]
Hello! 

Your $datesSource method does not returning anything... Try the following

```
 $datesSource = function($val){
        if($val == 1){
            return array(
                'NZ' => 'New Zealand',
                'US' => 'United States',
                'GEM'=> 'Germany'
            );
        }
        if($val == 2){
            return array(
                'NZ' => 'New Zealand',
                'US' => 'United States',
                'GEM'=> 'Germany'
            );
        }
    };
```
