### ISSUE TITLE
Problem with frontend form

### ISSUE THREAD

**Issue by StephaneAgenceCaza** [sheadawson/silverstripe-dependentdropdownfield#7]
Hi! I see a problem when using to module on a frontend form. DependentDropDownField array doesnt load on page load. But it work when changing the DropDownField... on backend cms all works perfectly.
There is my code on the frontend :

	$DropdownChoices2 = function($val){ 
			$Categories = ChoixCategoriesMembre::get();
			foreach ( $Categories as $Categorie ) {
				if($val == $Categorie->ID){
					$SousCategorie = ChoixSousCategoriesMembre::get()->filter('ChoixCategoriesMembresID', $Categorie->ID);
					return $SousCategorie->sort("Title","ASC")->map("ID", "Title");
			}
		}; 

	$fields->push(
		$Dropdown = new DropdownField('Categorie','Catégorie', Dataobject::get("ChoixCategoriesMembre")->map("ID", "Title") )	);
	$fields->push(
		
	 	$Dropdown2 = new DependentDropdownField('SousCategorie','Sous catégorie', $DropdownChoices2 )	);
		$Dropdown2->setDepends($Dropdown);

**Comment by sheadawson** [comment]
I couldn't replicate your frontend/backend issue. But this did bring a bug to my attention. If the DropdownField does not have a value set, and does not have an emptyDefaultString, the DependentDropdownField should have loaded the options based on the first value of the DropdownField. I have now fixed this and committed the change to the master branch. Does this fix your problem?

**Comment by StephaneAgenceCaza** [comment]
Thank for fast reply! The change didn't correct my problem. I will show some screenshoot for explanation.

Backend (Works well) 
![image](https://cloud.githubusercontent.com/assets/13698713/9148804/9cbfc85e-3d58-11e5-828b-e95ddd340c28.png)

Frontend (With the use of Member profil module)
![image](https://cloud.githubusercontent.com/assets/13698713/9148809/dbea75ba-3d58-11e5-92cd-1880028265d4.png)

If I change the DropDownField to another value and rechange it back, the DependentDropDownField works but not set the saved value if you see it in my backend screenshot
![image](https://cloud.githubusercontent.com/assets/13698713/9148821/64627ba4-3d59-11e5-8199-3357a73475b8.png)

**Comment by StephaneAgenceCaza** [comment]
Ok I have fix the problem... On frontend,I have added to the DropDownField the default value. I have added this code to correct my problem. 
Code added

	Member::currentUser()->Categorie

//

	$fields->push(
		$Dropdown = new DropdownField('Categorie','Catégorie', Dataobject::get("ChoixCategoriesMembre")->map("ID", "Title"), Member::currentUser()->Categorie  )	);

Thank for fix the bug!

**Comment by sheadawson** [comment]
Glad you worked it out!

**Comment by MrMirCannae** [comment]
Hi,
I have a similar problem. In backend it works fine and in frontend not.
Her is my code:
`       $typeField = \SilverStripe\Forms\DropdownField::create(
                'ProductType',
                'Product Type',
                [
                    'animal' => 'Animal',
                    'food' => 'Food'
                ]
        );
        $typeField->setEmptyString('Please select a product type');

        $productFieldSource = function($value) {
            if ($value === 'animal') {
                return [
                        'puppy' => 'Puppy',
                        'dog' => 'Dog',

                        'cat' => 'Cat'
                    
                ];
            }
            if ($value === 'food') {
                return [
                    'apple' => 'Apple',
                        'orange' => 'Orange',
                    
                    'carrot' => 'Carrot',
                    'celery' => 'Celery'
                ];
            }
            return [];
        };

        $productField = \Sheadawson\DependentDropdown\Forms\DependentDropdownField::create(
                'Product',
                'Product',
                $productFieldSource
        );

        $productField->setDepends($typeField);

        $fields = FieldList::create([$typeField, $productField]);
        $actions = FieldList::create(FormAction::create('add', 'add'));
        //$validator = new RequiredFields('fkTeilnehmerAbsender');

        $form = new Form($this, 'addForm', $fields, $actions);`

Can anyone help me?
